In [2]:
# import libraries
import pandas as pd
import numpy as np

### **Question 1**
What's the version of Pandas that you installed?

In [3]:
# check the version of pandas
print("The version of Pandas that installed:", pd.__version__)

The version of Pandas that installed: 2.2.2


### **Getting the Data**

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-02 21:42:33--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

     0K .......... .......... .......... .......... .......... 17% 62.5K 4s
    50K .......... .......... .......... .......... .......... 34%  107K 2s
   100K .......... .......... .......... .......... .......... 51% 73.3K 2s
   150K .......... .......... .......... .......... .......... 68% 75.6K 1s
   200K .......... .......... .......... .......... .......... 85% 91.7K 1s
   250K .......... .......... .......... .......... .         100%  106K=3.5s

2024-10-02 21:42:38 (82.2 KB/s) - 'laptops.csv' saved [298573/298573]



In [6]:
# initialize dataset
df = pd.read_csv('laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

### **Question 2**
How many records are in the dataset?

In [12]:
num_records = df.shape[0]

print(f"There are {num_records} records in the dataset.")

There are 2160 records in the dataset.


### **Question 3**
How many laptops brand are presented in the dataset?

In [13]:
n_laptop_brands = df['Laptop'].nunique()

print(f"There are {n_laptop_brands} unique laptop brands in the dataset")

There are 2160 unique laptop brands in the dataset


### **Question 4**
How many columns in the dataset have missing values?

In [14]:
n_missing_columns = df.isna().any().sum()

print(f"There are {n_missing_columns} columns that have missing values")

There are 3 columns that have missing values


### **Question 5**
What's the maximum final price of Dell notebooks in the dataset?

In [28]:
max_price_dell = df[df['Brand'] == 'Dell']['Final Price'].max()

print(f"There are {n_missing_columns} columns that have missing values")

There are 3 columns that have missing values


### **Question 6**
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.

Has it changed?

In [34]:
median_screen = df['Screen'].median()
print(f"The median of Screen: {median_screen}")

mode_screen = df['Screen'].mode()[0]
print(f"The mode of Screen: {mode_screen}")

df['Screen']= df['Screen'].fillna(mode_screen)
median_screen = df['Screen'].median()
print(f"The median of Screen: {median_screen}")

The median of Screen: 15.6
The mode of Screen: 15.6
The median of Screen: 15.6


### **Question 6**
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

In [46]:
innjoo_df = df.loc[df['Brand'] == "Innjoo", ['RAM', 'Storage', 'Screen']]
X = innjoo_df.values
print(f"Matrix X:\n", X)
print()

XTX = X.T.dot(X)
print(f"Matrix-Matrix Multiplication XTX:\n", XTX)
print()

inv_XTX = np.linalg.inv(XTX)
print(f"The inverse of XTX:\n", inv_XTX)
print()

y = np.array([1100, 1300, 800, 900, 1000, 1100])

w = inv_XTX.dot(X.T).dot(y)
print(f"The value of w:\n", w)
print()

total_w = w.sum()
print(f"The sum of all the elemnts of the result:", total_w)

Matrix X:
 [[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]

Matrix-Matrix Multiplication XTX:
 [[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]

The inverse of XTX:
 [[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]

The value of w:
 [45.58076606  0.42783519 45.29127938]

The sum of all the elemnts of the result: 91.2998806299555
